{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b2d846ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import psycopg2 as pg\n",
    "from psycopg2 import sql\n",
    "from sqlalchemy import create_engine\n",
    "import io"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85a05be8",
   "metadata": {},
   "outputs": [],
   "source": [
    "conn = pg.connect('host=localhost port=5432 dbname=postgres user=postgres password=postgres')\n",
    "conn.autocommit = True\n",
    "\n",
    "cur = conn.cursor()\n",
    "# sql.SQL and sql.Identifier are needed to avoid SQL injection attacks.\n",
    "cur.execute(sql.SQL('CREATE DATABASE comercio_exterior;'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "23fe1242",
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/comercio_exterior')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08ebc1ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "pasta_exportacao = '../../../../datalake/gold/agreg_exportacao'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3e68c91b",
   "metadata": {},
   "outputs": [],
   "source": [
    "arquivos_csv = [f for f in os.listdir(pasta_exportacao) if f.endswith('.csv')]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4390c9a3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enviando volume_exp_produto.csv para a tabela 'volume_exp_produto'...\n",
      " Erro ao enviar volume_exp_produto para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando vias_transporte.csv para a tabela 'vias_transporte'...\n",
      " Erro ao enviar vias_transporte para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando exp_uf_mun.csv para a tabela 'exp_uf_mun'...\n",
      " Erro ao enviar exp_uf_mun para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando produtos_top_10.csv para a tabela 'produtos_top_10'...\n",
      " Erro ao enviar produtos_top_10 para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Enviando volume_exp_mes.csv para a tabela 'volume_exp_mes'...\n",
      " Erro ao enviar volume_exp_mes para o banco: (psycopg2.OperationalError) connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Todos os arquivos foram enviados para o banco com sucesso.\n"
     ]
    }
   ],
   "source": [
    "for arquivo in arquivos_csv:\n",
    "    caminho_completo = os.path.join(pasta_exportacao, arquivo)\n",
    "    nome_tabela = os.path.splitext(arquivo)[0]\n",
    "\n",
    "    print(f\"Enviando {arquivo} para a tabela '{nome_tabela}'...\")\n",
    "\n",
    "    try:\n",
    "        with open(caminho_completo, 'rb') as f:\n",
    "            content = f.read()\n",
    "\n",
    "        # Decodifica substituindo caracteres inválidos\n",
    "        decoded_content = content.decode('latin1', errors='replace')\n",
    "\n",
    "        # Converte string limpa para \"arquivo virtual\" e lê com pandas\n",
    "        df = pd.read_csv(io.StringIO(decoded_content))\n",
    "    except Exception as e:\n",
    "        print(f\" Erro ao ler {arquivo}: {e}\")\n",
    "        continue\n",
    "\n",
    "    # Envia para o banco\n",
    "    try:\n",
    "        df.to_sql(name=nome_tabela, con=engine,  schema='exportacao', if_exists='replace', index=False)\n",
    "        print(f\" {nome_tabela} enviada com sucesso.\")\n",
    "    except Exception as e:\n",
    "        print(f\" Erro ao enviar {nome_tabela} para o banco: {e}\")\n",
    "\n",
    "print(\"Todos os arquivos foram enviados para o banco com sucesso.\")\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
